sbatch XGBoost/slurm_start.sh
sbatch SVRegression/slurm_start.sh
sbatch RandomForrest/slurm_start.sh
sbatch MLP/slurm_start.sh
sbatch LogisticRegression/slurm_start.sh
sbatch LassoRegression/slurm_start.sh
sbatch KNN/slurm_start.sh
sbatch EleasticNet/slurm_start.sh
sbatch CatBoost/slurm_start.sh
sbatch BaggedKNN/slurm_start.sh